/** @type {import('tailwindcss').Config} */
// Theme ported from the original mockup (marketing/mockup.html). The mockup loaded
// Tailwind from the CDN with an inline config; this is the production equivalent.
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#472a00",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-error": "#690005",
        primary: "#f59e0b",
        surface: "#131313",
        secondary: "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary": "#003824",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "primary-fixed": "#ffddb8",
        "inverse-on-surface": "#313030",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "secondary-container": "#00a572",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#201f1f",
        "surface-bright": "#3a3939",
        "on-primary-container": "#613b00",
        tertiary: "#ffbcb7",
        "on-tertiary-fixed": "#410004",
        "inverse-primary": "#855300",
        "on-primary-fixed": "#2a1700",
        "primary-container": "#f59e0b",
        "on-secondary-container": "#00311f",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#005236",
        error: "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#8d0012",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#ffdad7",
        background: "#131313",
        "text-muted": "#A3A3A3",
        "secondary-fixed": "#6ffbbe",
        "surface-container-low": "#1c1b1b",
        "amber-glow": "rgba(245, 158, 11, 0.4)",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#ffb95f",
        "tertiary-container": "#ff938c",
        "primary-fixed-dim": "#ffb95f",
        "on-tertiary": "#68000a",
        "surface-border": "#262626",
        "on-surface-variant": "#d8c3ad",
        "outline-variant": "#534434",
        outline: "#a08e7a",
        "surface-elevated": "#1A1A1A",
        "on-tertiary-fixed-variant": "#930013",
        "on-primary-fixed-variant": "#653e00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "component-padding-y": "0.75rem",
        "component-padding-x": "1rem",
        "page-margin": "1.25rem",
        "stack-md": "1rem",
        "stack-lg": "1.5rem",
        gutter: "1rem",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "stats-number": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        display: ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["22px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "stats-number": ["24px", { lineHeight: "1", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        display: ["36px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
